-- 1. Product Lines (The Chassis & Brand)
-- This holds the qualitative data that applies to the entire family of laptops.
CREATE TABLE product_lines (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    manufacturer VARCHAR(100) NOT NULL,
    line_name VARCHAR(100) NOT NULL, -- e.g., "ThinkPad T14 Gen 4"
    target_personas JSONB, -- e.g., '["student", "office_worker"]'
    llm_aggregated_scores JSONB, -- The final scores calculated from raw reviews
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (manufacturer, line_name)
);

-- Index the scores so you can quickly query "Find laptops with build_quality > 8"
CREATE INDEX idx_product_lines_scores ON product_lines USING GIN (llm_aggregated_scores);


-- 2. Specific SKUs (The Purchasable Hardware)
-- This holds the exact configurations and links back to the parent Product Line.
CREATE TABLE laptop_skus (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_line_id UUID REFERENCES product_lines(id) ON DELETE CASCADE,
    sku_number VARCHAR(100) UNIQUE NOT NULL,
    hardware_specs JSONB NOT NULL, -- Contains CPU, RAM, SSD, Display specs
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Index the hardware specs to allow fast filtering by RAM or CPU
CREATE INDEX idx_laptop_skus_specs ON laptop_skus USING GIN (hardware_specs);


-- 3. Price History
-- An append-only table to track price fluctuations over time.
CREATE TABLE price_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    laptop_sku_id UUID REFERENCES laptop_skus(id) ON DELETE CASCADE,
    vendor VARCHAR(50) NOT NULL, -- e.g., "Amazon", "BestBuy"
    price_usd NUMERIC(10, 2) NOT NULL,
    purchase_url TEXT NOT NULL,
    is_refurbished BOOLEAN DEFAULT FALSE,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- 4. Raw Scrapes (The ETL Staging Ground)
-- This is where your crawler dumps raw Reddit threads and where the LLM writes its JSON output.
CREATE TABLE raw_scrapes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_line_id UUID REFERENCES product_lines(id) ON DELETE SET NULL,
    source_url TEXT NOT NULL,
    source_platform VARCHAR(50) NOT NULL, -- e.g., "Reddit", "Notebookcheck"
    raw_text_content TEXT, -- The messy, unparsed HTML or text
    llm_parsed_json JSONB, -- The structured output generated by your LLM
    scraped_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    parsed_at TIMESTAMP WITH TIME ZONE
);
