-- 1. Product Lines (The Chassis & Subjective Qualities)
-- This table now strictly handles the "Extra things they value" (Battery, Build, Brand)
CREATE TABLE product_lines (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    manufacturer VARCHAR(100) NOT NULL,
    line_name VARCHAR(100) NOT NULL, 
    llm_aggregated_scores JSONB, -- e.g., '{"battery_life": 9.0, "build_quality": 8.5}'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (manufacturer, line_name)
);

CREATE INDEX idx_product_lines_scores ON product_lines USING GIN (llm_aggregated_scores);

-- 2. Specific SKUs (The Hardware & Objective Capabilities)
-- This table now holds the workload classifications
CREATE TABLE laptop_skus (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_line_id UUID REFERENCES product_lines(id) ON DELETE CASCADE,
    sku_number VARCHAR(100) UNIQUE NOT NULL,
    hardware_specs JSONB NOT NULL, 
    workload_scores JSONB, -- e.g., '{"web_browsing": 10, "3d_modeling": 0, "photo_editing": 5}'
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_laptop_skus_workloads ON laptop_skus USING GIN (workload_scores);

-- 3. Price History
-- An append-only table to track price fluctuations over time.
CREATE TABLE price_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    laptop_sku_id UUID REFERENCES laptop_skus(id) ON DELETE CASCADE,
    vendor VARCHAR(50) NOT NULL, -- e.g., "Amazon", "Ebay"
    price_usd NUMERIC(10, 2) NOT NULL,
    purchase_url TEXT NOT NULL,
    is_refurbished BOOLEAN DEFAULT FALSE,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Raw Scrapes 
-- 
CREATE TABLE raw_scrapes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_line_id UUID REFERENCES product_lines(id) ON DELETE SET NULL,
    source_url TEXT NOT NULL,
    source_platform VARCHAR(50) NOT NULL, -- e.g., "iFixit", "Notebookcheck"
    raw_text_content TEXT, -- The messy, unparsed HTML or text
    llm_parsed_json JSONB, -- The structured output generated by LLM
    scraped_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    parsed_at TIMESTAMP WITH TIME ZONE
);
